Repository sihyonn/sprint-part2-rollingProject, pull requests merged in 2024-03, with the labels that each got.

#55 PaperViewerPage 초안(레이아웃)
  public/index.html
  src/components/common/Card.jsx
  src/components/header/Header.jsx
  src/components/header/SharedButton.jsx
  src/components/header/SharedOption.jsx
  src/components/template/Layout.jsx
  src/components/template/PaperLayout.jsx
  src/hooks/useKakaoShare.js
  src/pages/PaperViewerPage.jsx
  src/router.js
  src/styles/commonStyle.js
  src/styles/theme.js
  src/utils/copyToClipBoard.js
  src/utils/formatDate.js
Labels: bug🐞, enhancement✨

#52 Feat: 롤링페이퍼 생성 페이지 UI 구현
  src/components/common/CardSample.jsx
  src/components/common/Input.jsx
  src/components/common/Option.jsx
  src/components/common/ToggleButton.jsx
  src/components/common/button/Button.jsx
  src/components/common/button/IconButton.jsx
  src/constants/BUTTON_STATUS.js
  src/constants/DROPDOWN_DATA.js
  src/constants/PLACEHOLDER.js
  src/pages/CreatePaperPage.jsx
Labels: enhancement✨

#30 Feat:관계를 나타내는 뱃지 구현
  src/components/common/RelationBadge.jsx
  src/pages/Hi.jsx
Labels: enhancement✨, common👨‍👨‍👧‍👧

#60 리액트 쿼리 셋팅, 커스텀 훅 구현 및 테스트
  src/App.jsx
  src/api/recipientsAPI.js
  src/components/common/Toast.jsx
  src/constants/API.js
  src/hooks/api/imagesAPI/useImagesQuery.js
  src/hooks/api/messagesAPI/useTest.js
  src/hooks/api/recipientsAPI/usePostRecipientMutation.js
  src/pages/CreatePaperPage.jsx
  src/pages/Hi.jsx
  src/pages/Sh.jsx
Labels: enhancement✨

#58 Feat: LandingPage구현
  src/assets/EmojiExample.svg
  src/assets/mobileCard.svg
  src/assets/pcCard.svg
  src/components/common/Gnb.jsx
  src/components/header/EmojiAddButton.jsx
  src/pages/MainPage.jsx
Labels: enhancement✨

#62 Feat: 메세지 작성하는 페이지 UI 구현
  src/components/common/TextEditor.jsx
  src/components/common/badge/ProfileBadgeCard.jsx
  src/components/common/badge/ProfileBadgeSelect.jsx
  src/components/common/form/Dropdown.jsx
  src/pages/WirteMessagePage.jsx
  src/pages/WriteMessagePage.jsx
  src/router.js
Labels: enhancement✨

#65 API 경로 누락 fix
  src/constants/API.js
Labels: bug🐞

#69 PaperViewerPage 구현
  src/api/recipientsAPI.js
  src/components/common/button/IconButton.jsx
  src/components/common/modal/BackdropModal.jsx
  src/components/rollingPaperViewer/AddCard.jsx
  src/components/rollingPaperViewer/Card.jsx
  src/components/rollingPaperViewer/DetailCardModal.jsx
  src/components/rollingPaperViewer/InfiniteCardMessages.jsx
  src/components/template/PaperLayout.jsx
  src/hooks/api/messagesAPI/useInfiniteCardMessagesQuery.js
  src/hooks/api/messagesAPI/useTest.js
  src/hooks/useIntersectionObserver.js
  src/pages/PaperViewerPage.jsx
  src/utils/formatDate.js
Labels: bug🐞, enhancement✨

#72 api 경로, interceptor 공통에러처리 버그 처리
  src/api/instance.js
  src/constants/API.js
Labels: bug🐞

#73 Feat: Header api연동 및 ui 수정
  src/components/header/EmojiAddButton.jsx
  src/components/header/EmojiExpand.jsx
  src/components/header/EmojiList.jsx
  src/components/header/EmojiOption.jsx
  src/components/header/Header.jsx
  src/components/header/ProfileBadgeFirst.jsx
  src/components/header/ProfileBadgeSecond.jsx
  src/components/header/ProfileBadgeThird.jsx
  src/hooks/api/recipientsAPI/useGetReactions.js
  src/hooks/api/recipientsAPI/useGetRecipients.js
  src/hooks/api/recipientsAPI/usePostRecipient.js
  src/hooks/useKakaoShare.js
Labels: enhancement✨

#77 Fix: styled props 관련 수정
  src/components/header/ProfileBadgeFirst.jsx
  src/components/header/ProfileBadgeSecond.jsx
  src/components/header/ProfileBadgeThird.jsx
  src/pages/MainPage.jsx
Labels: fix

#78 PaperEditPage api 연동완료
  src/components/rollingPaperViewer/Card.jsx
  src/components/rollingPaperViewer/InfiniteCardMessages.jsx
  src/hooks/api/recipientsAPI/useDeleteMessageMutation.js
  src/hooks/api/recipientsAPI/useDeleteRecipientMutation.js
  src/pages/PaperEditPage.jsx
  src/pages/PaperViewerPage.jsx
Labels: enhancement✨, api🔑, layout💅🏻

#80 카드 목록 무한 스크롤 로더 구현
  src/components/rollingPaperViewer/Card.jsx
  src/components/rollingPaperViewer/CardMessagesSkeleton.jsx
  src/components/rollingPaperViewer/InfiniteCardMessages.jsx
  src/components/rollingPaperViewer/InfiniteCardMessagesLoader.jsx
  src/hooks/api/messagesAPI/useInfiniteCardMessagesQuery.js
  src/pages/PaperEditPage.jsx
  src/pages/PaperViewerPage.jsx
  src/styles/commonStyle.js
  src/styles/theme.js
Labels: bug🐞, enhancement✨

#86 Feat: 리스트페이지 api 구현 및 ui 추가 구현
  package-lock.json
  src/api/recipientsAPI.js
  src/assets/beige.svg
  src/assets/blue.svg
  src/assets/green.svg
  src/assets/purple.svg
  src/components/ListPage/AvatarList.jsx
  src/components/ListPage/CardItem.jsx
  src/components/ListPage/Carousel.jsx
  src/hooks/api/recipientsAPI/useGetRecipientsLikeList.js
  src/hooks/api/recipientsAPI/useGetRecipientsList.js
  src/pages/PaperListPage.jsx
Labels: api🔑

#87 Fix: 이미지 옵션에서 선택된 이미지 배경 처리 추가
  src/components/common/CardSample.jsx
  src/components/common/button/IconButton.jsx
Labels: api🔑

#89 Fix: header 부분 bug수정
  src/components/ListPage/AvatarList.jsx
  src/components/header/EmojiList.jsx
  src/components/header/Header.jsx
Labels: bug🐞, fix

#90 PaperViewer, PaperEdit 페이지 리팩토링
  src/components/common/QuillStrToHtml.jsx
  src/components/header/EmojiAddButton.jsx
  src/components/header/Header.jsx
  src/components/rollingPaperViewer/InfiniteCardMessages.jsx
  src/components/template/Layout.jsx
  src/components/template/MainLayout.jsx
  src/components/template/PaperCreationLayout.jsx
  src/components/template/PaperLayout.jsx
  src/hooks/api/messagesAPI/useInfiniteCardMessagesQuery.js
  src/hooks/api/recipientsAPI/usePostReactionMutation.js
  src/pages/Choi.jsx
  src/pages/Hi.jsx
  src/pages/Sh.jsx
  src/pages/TestPage.jsx
  src/pages/Yj.jsx
  src/router.js
  src/styles/commonStyle.js
Labels: bug🐞, refactoring🛠️

#93 Fix: 자잘한 버그 수정
  public/index.html
  src/components/ListPage/CardItem.jsx
  src/components/common/Gnb.jsx
  src/components/header/Header.jsx
  src/components/template/PaperLayout.jsx
  src/pages/MainPage.jsx
Labels: bug🐞

#97 Refactor: 반응형 디자인 세부 수정
  src/components/ListPage/CardItem.jsx
  src/components/ListPage/Carousel.jsx
  src/components/common/badge/EmojiBadge.jsx
  src/components/header/EmojiList.jsx
  src/components/header/Header.jsx
  src/pages/MainPage.jsx
  src/pages/PaperListPage.jsx
Labels: fix, refactoring🛠️

#100 글꼴 적용 및 gnb main list 페이지에서만 나오게 적용
  public/index.html
  src/components/common/Gnb.jsx
  src/components/common/QuillStrToHtml.jsx
  src/components/header/Header.jsx
Labels: bug🐞, fix

#102 [Fix] console 창에 있는 내용 지우기 + font contstants 폴더 변경
  src/components/common/QuillStrToHtml.jsx
  src/components/common/badge/ProfileBadgeCard.jsx
  src/components/template/PaperLayout.jsx
  src/constants/FONT.js
  src/pages/PaperListPage.jsx
Labels: fix, refactoring🛠️

#104 Feat: 리스트 페이지 스켈레톤 구현
  src/components/ListPage/CardItem.jsx
  src/components/ListPage/CardItemSke.jsx
  src/components/ListPage/Carousel.jsx
  src/components/ListPage/CarouselSke.jsx
Labels: enhancement✨

#107 [Refactor] 캐러셀 리팩토링 및 jsDoc 추가
  src/components/ListPage/AvatarList.jsx
  src/components/ListPage/CardItem.jsx
  src/components/ListPage/CardItemSke.jsx
  src/components/ListPage/Carousel.jsx
  src/components/ListPage/CarouselSke.jsx
Labels: refactoring🛠️

#108 onSelect 문제점 해결 및 cursor: pointer이상한 부분 없애기 및 이름 16자제한
  src/components/common/badge/ProfileBadgeCard.jsx
  src/components/common/button/IconButton.jsx
  src/components/common/form/Input.jsx
  src/components/common/modal/BackdropModal.jsx
  src/components/rollingPaperViewer/AddCard.jsx
  src/components/rollingPaperViewer/Card.jsx
  src/pages/CreatePaperPage.jsx
  src/pages/WriteMessagePage.jsx
Labels: refactoring🛠️

#109 편집완료 버튼구현, 스크롤 탑버튼 구현, 페이지 타이틀 설정
  src/assets/icon/ArrowTopIcon.jsx
  src/components/common/PageTitle.jsx
  src/components/common/button/IconButton.jsx
  src/components/list/AvatarList.jsx
  src/components/list/CardItem.jsx
  src/components/list/CardItemSke.jsx
  src/components/list/Carousel.jsx
  src/components/list/CarouselSke.jsx
  src/components/paperViewer/AddCard.jsx
  src/components/paperViewer/Card.jsx
  src/components/paperViewer/CardMessagesSkeleton.jsx
  src/components/paperViewer/DetailCardModal.jsx
  src/components/paperViewer/InfiniteCardMessages.jsx
  src/components/paperViewer/InfiniteCardMessagesLoader.jsx
  src/components/paperViewer/TopButton.jsx
  src/components/rollingPaperViewer/InfiniteCardMessages.jsx
  src/components/template/PaperLayout.jsx
  src/constants/BUTTON.js
  src/constants/MESSAGE.js
  src/constants/PLACEHOLDER.js
  src/hooks/useIntersectionObserver.js
  src/hooks/useScrollToTop.js
  src/pages/CreatePaperPage.jsx
  src/pages/MainPage.jsx
  src/pages/PaperEditPage.jsx
  src/pages/PaperListPage.jsx
  src/pages/PaperViewerPage.jsx
  src/pages/WriteMessagePage.jsx
  src/styles/commonStyle.js
  src/styles/quill.strToHtml.css
Labels: enhancement✨, refactoring🛠️

#110 useScrollToTop 의존성배열 관련 warning 해결
  src/hooks/useScrollToTop.js
Labels: bug🐞, fix

#112 Update README.md
  README.md
Labels: documentation📃
